---
deployment:
  tasks:
    # -------- Paths --------
    - export APP_PATH="$HOME/public_html"                 # Repo lives directly in public_html
    - export PHP="/opt/cpanel/ea-php82/root/usr/bin/php"  # Adjust if your PHP path differs

    # -------- Composer (production) --------
    - cd "$APP_PATH"
    - if command -v composer >/dev/null 2>&1; then
        composer install --no-dev --optimize-autoloader;
      else
        echo "Composer not found — skipping composer install";
      fi

    # -------- Vite build (if Node is available) --------
    - if command -v npm >/dev/null 2>&1; then
        rm -rf public/build;
        npm ci;
        npm run build;
      else
        echo "Node not found — skipping asset build (ensure public/build is committed if needed)";
      fi

    # -------- Storage: COPY files into /public/storage (no symlink) --------
    - rm -rf "$APP_PATH/public/storage"
    - mkdir -p "$APP_PATH/public/storage"
    - /bin/rsync -a "$APP_PATH/storage/app/public/" "$APP_PATH/public/storage/"
    - find "$APP_PATH/public/storage" -type d -exec chmod 755 {} \;
    - find "$APP_PATH/public/storage" -type f -exec chmod 644 {} \;

    # -------- Root index.php: forward to /public/index.php --------
    - printf "%s\n" "<?php" "require __DIR__ . '/public/index.php';" > "$APP_PATH/index.php"

    # -------- Root .htaccess: map /build & /storage to /public, protect app files --------
    - |-
      cat > "$APP_PATH/.htaccess" <<'HTACCESS'
      # Map asset paths at web root to the /public folder
      RewriteEngine On

      # Send /build/* and /storage/* to /public/*
      RewriteRule ^build/(.*)$ public/build/$1 [L]
      RewriteRule ^storage/(.*)$ public/storage/$1 [L]

      # Serve existing files/dirs directly
      RewriteCond %{REQUEST_FILENAME} -f [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^ - [L]

      # Protect sensitive Laravel paths/files
      RedirectMatch 404 ^/(?:app|bootstrap|config|database|resources|routes|tests|vendor)(/.*)?$
      RedirectMatch 404 ^/composer\.(json|lock)$
      RedirectMatch 404 ^/artisan$
      RedirectMatch 404 ^/\.env

      # Otherwise route to Laravel
      RewriteRule ^ public/index.php [L]
      HTACCESS

    # -------- Optimize caches (heavy clear only if .env changed) --------
    - export ENV_MD5_FILE="$APP_PATH/storage/framework/.env.md5"
    - export CURRENT_ENV_MD5="$(/usr/bin/md5sum "$APP_PATH/.env" 2>/dev/null | awk '{print $1}')"
    - export SAVED_ENV_MD5="$(cat "$ENV_MD5_FILE" 2>/dev/null || echo '')"
    - if [ "$CURRENT_ENV_MD5" != "$SAVED_ENV_MD5" ]; then
        echo ".env changed → optimize:clear + optimize";
        $PHP artisan optimize:clear || true;
        $PHP artisan optimize || true;
        $php artisan storage:link || true;
        echo "$CURRENT_ENV_MD5" > "$ENV_MD5_FILE";
      else
        echo ".env unchanged → light optimize";
        $PHP artisan optimize || true;
        $php artisan storage:link || true;
      fi

    # -------- (Optional) DB migrations --------
    # - $PHP artisan migrate --force || true
      

    - echo "✅ Deployment completed (public_html is the repo root)"
