---
deployment:
  tasks:
    # ---- Adjust these three to your account ----
    - export APP_PATH="$HOME/tenxglobal"                             # where artisan lives
    - export PUBLIC_HTML="$HOME/public_html"                         # web root
    - export PHP="/opt/cpanel/ea-php82/root/usr/bin/php"             # set to your PHP path

    # ---- Sync repo into APP_PATH (safe place, NOT web root) ----
    # $DEPLOYPATH is the temp checkout path cPanel gives you.
    - mkdir -p $APP_PATH
    - /bin/rsync -a --delete --exclude=".git" --exclude="node_modules" $DEPLOYPATH/ $APP_PATH/

    # ---- Composer prod install (optional if vendor is committed) ----
    - cd $APP_PATH
    - command -v composer >/dev/null 2>&1 && composer install --no-dev --optimize-autoloader || true

    # ---- First-time env setup (uncomment only the first deploy) ----
    # - [ -f .env ] || cp .env.example .env
    # - $PHP artisan key:generate
    # - $PHP artisan storage:link

    # ---- Database migrations (comment out if you don’t want auto-migrate) ----
    - $PHP artisan migrate --force || true

    # ---- Build assets (only if Node is available on server) ----
    - if command -v npm >/dev/null 2>&1; then rm -rf public/build && npm ci && npm run build; fi

    # ---- Publish ONLY public/ to public_html ----
    - /bin/rsync -a --delete $APP_PATH/public/ $PUBLIC_HTML/

    # ---- Optimize caches ----
    - $PHP artisan optimize

    - cd $APP_PATH
    - $PHP artisan storage:link || true
